[build]
builder = "nixpacks"

[deploy]
startCommand = "./bin/leo-bot"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Go specific configuration
[build.variables]
GO_VERSION = "1.21"
